/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pacote.code.frame;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import pacote.code.dao.EspecialidadeDAO;
import pacote.code.model.Especialidade;
import pacote.code.model.OperacaoEnum;

/**
 *
 * @author 22282173
 */
public class EspecialidadeDialog extends javax.swing.JDialog {

    private Especialidade especialidade;
    private OperacaoEnum operacao;

    public EspecialidadeDialog(java.awt.Frame parent, boolean modal, OperacaoEnum operacao) {
        super(parent, modal);
        initComponents();
        this.operacao = operacao;
        prencherTitulo();
    }

    public EspecialidadeDialog(java.awt.Frame parent, boolean modal, Especialidade e, OperacaoEnum operacao) {
        super(parent, modal);
        especialidade = e;
        this.operacao = operacao;
        initComponents();
        prencherTitulo();
        prencherFormulario();
    }

    private void prencherFormulario() {
        jtextfieldCodigo.setText(especialidade.getCodigo().toString());
        jtextfieldNomeEspecialidade.setText(especialidade.getNome());
        jtextfieldDescricaoEspecialidade.setText(especialidade.getDescricao());

    }

    
        private void prencherTitulo(){
     jlabelTitleDialog.setText("Especialidade " + operacao);
     if(operacao == OperacaoEnum.Editar){
     
          jlabelImgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/canetalogo.png")));
         
         
     }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelHeaderDialog = new javax.swing.JPanel();
        jlabelTitleDialog = new javax.swing.JLabel();
        jlabelImgLogo = new javax.swing.JLabel();
        jpanelMainDialog = new javax.swing.JPanel();
        jtextfieldCodigo = new javax.swing.JTextField();
        jtextfieldNomeEspecialidade = new javax.swing.JTextField();
        jtextfieldDescricaoEspecialidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalvarDiaolog = new javax.swing.JButton();
        btnCancelarDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(null);

        jpanelHeaderDialog.setBackground(new java.awt.Color(255, 153, 0));
        jpanelHeaderDialog.setLayout(null);

        jlabelTitleDialog.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlabelTitleDialog.setForeground(new java.awt.Color(255, 255, 255));
        jlabelTitleDialog.setText("Especialidades ADICIONAR");
        jpanelHeaderDialog.add(jlabelTitleDialog);
        jlabelTitleDialog.setBounds(70, 20, 310, 40);

        jlabelImgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/adicionarCoisas.png"))); // NOI18N
        jpanelHeaderDialog.add(jlabelImgLogo);
        jlabelImgLogo.setBounds(30, 20, 40, 40);

        getContentPane().add(jpanelHeaderDialog);
        jpanelHeaderDialog.setBounds(0, 0, 800, 70);

        jpanelMainDialog.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes da especialidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 102, 0))); // NOI18N
        jpanelMainDialog.setLayout(null);

        jtextfieldCodigo.setEditable(false);
        jtextfieldCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        jtextfieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldCodigoActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(jtextfieldCodigo);
        jtextfieldCodigo.setBounds(50, 60, 80, 30);

        jtextfieldNomeEspecialidade.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        jtextfieldNomeEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldNomeEspecialidadeActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(jtextfieldNomeEspecialidade);
        jtextfieldNomeEspecialidade.setBounds(50, 210, 460, 30);

        jtextfieldDescricaoEspecialidade.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        jtextfieldDescricaoEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldDescricaoEspecialidadeActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(jtextfieldDescricaoEspecialidade);
        jtextfieldDescricaoEspecialidade.setBounds(50, 130, 460, 30);

        jLabel1.setText("DESCRIÇÂO DA ESPECIALIDADE");
        jpanelMainDialog.add(jLabel1);
        jLabel1.setBounds(50, 190, 210, 16);

        jLabel2.setText("CODIGO");
        jpanelMainDialog.add(jLabel2);
        jLabel2.setBounds(50, 40, 50, 20);

        jLabel3.setText("NOME DA ESPECIALIDADE");
        jpanelMainDialog.add(jLabel3);
        jLabel3.setBounds(50, 110, 190, 16);

        btnSalvarDiaolog.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvarDiaolog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/salvar.png"))); // NOI18N
        btnSalvarDiaolog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDiaologActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(btnSalvarDiaolog);
        btnSalvarDiaolog.setBounds(630, 253, 50, 40);

        btnCancelarDialog.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/excluir (4).png"))); // NOI18N
        btnCancelarDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDialogActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(btnCancelarDialog);
        btnCancelarDialog.setBounds(570, 253, 50, 40);

        getContentPane().add(jpanelMainDialog);
        jpanelMainDialog.setBounds(40, 90, 700, 310);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfieldNomeEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldNomeEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldNomeEspecialidadeActionPerformed

    private void jtextfieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldCodigoActionPerformed

    private void jtextfieldDescricaoEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldDescricaoEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldDescricaoEspecialidadeActionPerformed

    private void btnSalvarDiaologActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDiaologActionPerformed
        // TODO add your handling code here:
    if(operacao == OperacaoEnum.Adicionar){
             adicionar();
    }else{
       editar();
    }
   
    
    
    
    }//GEN-LAST:event_btnSalvarDiaologActionPerformed
    private void editar(){
        especialidade.setNome(jtextfieldNomeEspecialidade.getText());
        especialidade.setDescricao(jtextfieldDescricaoEspecialidade.getText());
        EspecialidadeDAO.atualizar(especialidade);
        dispose();
    }
    
    
    
    private void adicionar(){
          Especialidade novaEspecialidade = new Especialidade();
        novaEspecialidade.setNome(jtextfieldNomeEspecialidade.getText());
        novaEspecialidade.setDescricao(jtextfieldDescricaoEspecialidade.getText());
        // Gravar o objeto, através do dao
        EspecialidadeDAO.gravar(novaEspecialidade);
        JOptionPane.showMessageDialog(this, "Gravado Com sucesso", " Especialidade", JOptionPane.INFORMATION_MESSAGE);
        dispose();

    }                
    
  
    private void btnCancelarDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDialogActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarDialogActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarDialog;
    private javax.swing.JButton btnSalvarDiaolog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlabelImgLogo;
    private javax.swing.JLabel jlabelTitleDialog;
    private javax.swing.JPanel jpanelHeaderDialog;
    private javax.swing.JPanel jpanelMainDialog;
    private javax.swing.JTextField jtextfieldCodigo;
    private javax.swing.JTextField jtextfieldDescricaoEspecialidade;
    private javax.swing.JTextField jtextfieldNomeEspecialidade;
    // End of variables declaration//GEN-END:variables
}
