/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pacote.code.frame;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import pacote.code.dao.MedicoDAO;
import pacote.code.model.Medico;
import pacote.code.model.OperacaoEnum;

/**
 *
 * @author ander
 */
public class MedicoPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicoPanelTeste
     */
    public MedicoPanel() {
        initComponents();
        MedicoDAO.criarListaDeMedicos();
        ajustarTabela();
        prencherTabela();
    }

    private int linha;

    private int getLinha() {
        linha = tabelaMedico.getSelectedRow();
        return linha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        jpanelHomeMedico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMedico = new javax.swing.JTable();
        btnLimparMedico = new javax.swing.JButton();
        btnEditarMedico = new javax.swing.JButton();
        btnAdicionarMedico = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEspecialidades1 = new javax.swing.JTable();
        btnLimpar1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnAdicionar1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(null);

        jpanel.setLayout(null);

        jpanelHomeMedico.setBackground(new java.awt.Color(255, 255, 255));
        jpanelHomeMedico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Médicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 102, 0))); // NOI18N
        jpanelHomeMedico.setForeground(new java.awt.Color(255, 255, 255));

        tabelaMedico.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        tabelaMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaMedico.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaMedico);

        javax.swing.GroupLayout jpanelHomeMedicoLayout = new javax.swing.GroupLayout(jpanelHomeMedico);
        jpanelHomeMedico.setLayout(jpanelHomeMedicoLayout);
        jpanelHomeMedicoLayout.setHorizontalGroup(
            jpanelHomeMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelHomeMedicoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jpanelHomeMedicoLayout.setVerticalGroup(
            jpanelHomeMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelHomeMedicoLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpanel.add(jpanelHomeMedico);
        jpanelHomeMedico.setBounds(30, 10, 820, 350);
        jpanelHomeMedico.getAccessibleContext().setAccessibleDescription("");

        btnLimparMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/excluir (1).png"))); // NOI18N
        btnLimparMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparMedicoActionPerformed(evt);
            }
        });
        jpanel.add(btnLimparMedico);
        btnLimparMedico.setBounds(640, 360, 60, 31);

        btnEditarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/caneta.png"))); // NOI18N
        btnEditarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMedicoActionPerformed(evt);
            }
        });
        jpanel.add(btnEditarMedico);
        btnEditarMedico.setBounds(700, 360, 60, 31);

        btnAdicionarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/plus.png"))); // NOI18N
        btnAdicionarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMedicoActionPerformed(evt);
            }
        });
        jpanel.add(btnAdicionarMedico);
        btnAdicionarMedico.setBounds(760, 360, 70, 31);

        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Especialidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        tabelaEspecialidades1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        tabelaEspecialidades1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaEspecialidades1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaEspecialidades1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 10, 820, 350);

        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/excluir (1).png"))); // NOI18N
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpar1);
        btnLimpar1.setBounds(630, 370, 30, 31);

        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/caneta.png"))); // NOI18N
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar1);
        btnEditar1.setBounds(690, 370, 30, 31);

        btnAdicionar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/plus.png"))); // NOI18N
        btnAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdicionar1);
        btnAdicionar1.setBounds(750, 370, 30, 31);

        jpanel.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        add(jpanel);
        jpanel.setBounds(0, 0, 830, 431);

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparMedicoActionPerformed
        // TODO add your handling code here:
        getLinha();
        if (getLinha() != -1) {
            excluirMedico();
        } else {
            JOptionPane.showMessageDialog(this,
                "Nenhuma linha selecionada, Por favor Selecione!!",
                "Atenção", JOptionPane.WARNING_MESSAGE,
                null
            );
        }
    }//GEN-LAST:event_btnLimparMedicoActionPerformed

    private void btnEditarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMedicoActionPerformed
        // TODO add your handling code here:

        if (getLinha() != -1) {
            editarMedico();

        } else {
            JOptionPane.showMessageDialog(null,
                "Por favor clique na especialidade desejavel",
                "Atenção",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarMedicoActionPerformed

    private void btnAdicionarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMedicoActionPerformed
        // TODO add your handling code here:
        //       PlanoDeSaudeDialog planoDeSaudeDialog = new PlanoDeSaudeDialog(null, true, OperacaoEnum.Adicionar);
        //        planoDeSaudeDialog.setVisible(true);
        //        prencherTabela();
        MedicoDialog medicodialog = new MedicoDialog(null, true, OperacaoEnum.Adicionar);
        medicodialog.setVisible(true);
        prencherTabela();
    }//GEN-LAST:event_btnAdicionarMedicoActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar1ActionPerformed
        // TODO add your handling code here:
        
//         PlanoDeSaudeDialog planoDeSaudeDialog = new PlanoDeSaudeDialog(null, true, OperacaoEnum.Adicionar);
//        planoDeSaudeDialog.setVisible(true);
//        prencherTabela();

        MedicoDialog medicodialog = new MedicoDialog(null, true, OperacaoEnum.Adicionar);
        medicodialog.setVisible(true);
        prencherTabela();
                
    }//GEN-LAST:event_btnAdicionar1ActionPerformed
    private void excluirMedico() {

        getLinha();

        int resposta = JOptionPane.showConfirmDialog(this,
                "Você deseja escluir esse Plano De Saúde",
                "Confirmação", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (resposta == 0) {
            MedicoDAO.excluirMedico(getCodigo());
            prencherTabela();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar1;
    private javax.swing.JButton btnAdicionarMedico;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEditarMedico;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnLimparMedico;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpanel;
    private javax.swing.JPanel jpanelHomeMedico;
    private javax.swing.JTable tabelaEspecialidades1;
    private javax.swing.JTable tabelaMedico;
    // End of variables declaration//GEN-END:variables

    private void prencherTabela() {

        tabelaMedico.setModel(MedicoDAO.getMedicoModel());
        ajustarTabela();

    }

    private void ajustarTabela() {
        tabelaMedico.getTableHeader().setReorderingAllowed(false);
        tabelaMedico.setDefaultEditor(Object.class, null);
        tabelaMedico.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelaMedico.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaMedico.getColumnModel().getColumn(2).setPreferredWidth(200);
        tabelaMedico.getColumnModel().getColumn(3).setPreferredWidth(330);
        tabelaMedico.getColumnModel().getColumn(3).setPreferredWidth(270);
        tabelaMedico.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

    }

    private Integer getCodigo() {
        String codigoStr = tabelaMedico.getValueAt(getLinha(), 0).toString();
        Integer codigo = Integer.valueOf(codigoStr);
        return codigo;
    }

    private void editarMedico() {

        Medico medico = MedicoDAO.getMedico(getCodigo());
        MedicoDialog medicoDialog = new MedicoDialog(null, true, medico, OperacaoEnum.Editar);
        medicoDialog.setVisible(true);
        prencherTabela();
    }

}
