/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pacote.code.frame;

import javax.swing.JOptionPane;
import pacote.code.dao.MedicoDAO;
import pacote.code.model.Medico;
import pacote.code.model.OperacaoEnum;

/**
 *
 * @author ander
 */
public class MedicoDialog extends javax.swing.JDialog {

    private Medico medico;
    private OperacaoEnum operacao;

    /**
     * Creates new form MedicoDialog
     */
    public MedicoDialog(java.awt.Frame parent, boolean modal, OperacaoEnum operacao) {
        super(parent, modal);
        initComponents();
        this.operacao = operacao;
        prencherTitulo();
    }

    public MedicoDialog(java.awt.Frame parent, boolean modal, Medico medico, OperacaoEnum operacao) {
        super(parent, modal);
        initComponents();
        this.medico = medico;
        this.operacao = operacao;
        prencherTitulo();
        prencherFormulario();
    }

    private void prencherFormulario() {
        jtexfieldCodigo.setText(medico.getCodigo().toString());
        jtextfieldNome.setText(medico.getNome());
        jtextfieldCrm.setText(medico.getCrm());
        jtexfieldEmail.setText(medico.getEmail());
        jtextfieldTelefone.setText(medico.getTelefone());
    }

    private void prencherTitulo() {
        jlabelTitleDialog.setText("Medico " + operacao);
        if (operacao == OperacaoEnum.Editar) {

            jlabelImgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/canetalogo.png")));

        }

    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelHeaderDialog = new javax.swing.JPanel();
        jlabelTitleDialog = new javax.swing.JLabel();
        jlabelImgLogo = new javax.swing.JLabel();
        jpanelMainDialog = new javax.swing.JPanel();
        jlabelValidade = new javax.swing.JLabel();
        jlabelTelefone = new javax.swing.JLabel();
        btnSalvarDiaolog = new javax.swing.JButton();
        btnCancelarDialog = new javax.swing.JButton();
        jformattedData = new javax.swing.JFormattedTextField();
        jlabelCodigo1 = new javax.swing.JLabel();
        jlabelCrm = new javax.swing.JLabel();
        jlabelEmail = new javax.swing.JLabel();
        jlabelNome2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JlistEspecialidadeMedico = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JlistListadeEspecialidadades = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        JButtonMoverEspecialidade = new javax.swing.JButton();
        JbuttonRemoverEspecialidade = new javax.swing.JButton();
        jtextfieldNome = new javax.swing.JTextField();
        jtexfieldCodigo = new javax.swing.JTextField();
        jtexfieldEmail = new javax.swing.JTextField();
        jtextfieldCrm = new javax.swing.JTextField();
        jtextfieldTelefone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jpanelHeaderDialog.setBackground(new java.awt.Color(255, 153, 0));
        jpanelHeaderDialog.setLayout(null);

        jlabelTitleDialog.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlabelTitleDialog.setForeground(new java.awt.Color(255, 255, 255));
        jlabelTitleDialog.setText("Plano de Saude Adicionar ");
        jpanelHeaderDialog.add(jlabelTitleDialog);
        jlabelTitleDialog.setBounds(70, 20, 310, 40);

        jlabelImgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/adicionarCoisas.png"))); // NOI18N
        jpanelHeaderDialog.add(jlabelImgLogo);
        jlabelImgLogo.setBounds(30, 20, 40, 40);

        jpanelMainDialog.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes do Médico"));
        jpanelMainDialog.setLayout(null);

        jlabelValidade.setText("DATA");
        jpanelMainDialog.add(jlabelValidade);
        jlabelValidade.setBounds(470, 90, 60, 16);

        jlabelTelefone.setText("TELEFONE");
        jpanelMainDialog.add(jlabelTelefone);
        jlabelTelefone.setBounds(50, 90, 60, 20);

        btnSalvarDiaolog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/salvar.png"))); // NOI18N
        btnSalvarDiaolog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDiaologActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(btnSalvarDiaolog);
        btnSalvarDiaolog.setBounds(550, 260, 50, 40);

        btnCancelarDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/excluir (4).png"))); // NOI18N
        btnCancelarDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDialogActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(btnCancelarDialog);
        btnCancelarDialog.setBounds(490, 260, 50, 40);

        jformattedData.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        try {
            jformattedData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jformattedData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jformattedData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jformattedDataActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(jformattedData);
        jformattedData.setBounds(470, 110, 70, 30);

        jlabelCodigo1.setText("CODIGO");
        jpanelMainDialog.add(jlabelCodigo1);
        jlabelCodigo1.setBounds(50, 40, 50, 20);

        jlabelCrm.setText("CRM");
        jpanelMainDialog.add(jlabelCrm);
        jlabelCrm.setBounds(160, 40, 50, 20);

        jlabelEmail.setText("EMAIL");
        jpanelMainDialog.add(jlabelEmail);
        jlabelEmail.setBounds(210, 90, 50, 20);

        jlabelNome2.setText("NOME DO(A) MÉDICO(A)");
        jpanelMainDialog.add(jlabelNome2);
        jlabelNome2.setBounds(260, 40, 150, 20);

        JlistEspecialidadeMedico.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        JlistEspecialidadeMedico.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JlistEspecialidadeMedico);

        jpanelMainDialog.add(jScrollPane1);
        jScrollPane1.setBounds(260, 190, 150, 100);

        jLabel1.setText("ESPECIALIDADE DO MÉDICO");
        jpanelMainDialog.add(jLabel1);
        jLabel1.setBounds(260, 170, 160, 16);

        JlistListadeEspecialidadades.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        JlistListadeEspecialidadades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(JlistListadeEspecialidadades);

        jpanelMainDialog.add(jScrollPane2);
        jScrollPane2.setBounds(60, 190, 130, 100);

        jLabel2.setText("LISTA DE ESPECIALIDADE");
        jpanelMainDialog.add(jLabel2);
        jLabel2.setBounds(60, 170, 140, 16);

        JButtonMoverEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/right-arrow (1).png"))); // NOI18N
        jpanelMainDialog.add(JButtonMoverEspecialidade);
        JButtonMoverEspecialidade.setBounds(200, 190, 50, 40);

        JbuttonRemoverEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/excluir (4).png"))); // NOI18N
        JbuttonRemoverEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonRemoverEspecialidadeActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(JbuttonRemoverEspecialidade);
        JbuttonRemoverEspecialidade.setBounds(200, 250, 50, 40);

        jtextfieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldNomeActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(jtextfieldNome);
        jtextfieldNome.setBounds(260, 60, 190, 30);

        jtexfieldCodigo.setEditable(false);
        jtexfieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtexfieldCodigoActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(jtexfieldCodigo);
        jtexfieldCodigo.setBounds(50, 60, 90, 30);

        jtexfieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtexfieldEmailActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(jtexfieldEmail);
        jtexfieldEmail.setBounds(210, 110, 200, 30);

        jtextfieldCrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldCrmActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(jtextfieldCrm);
        jtextfieldCrm.setBounds(160, 60, 90, 30);

        jtextfieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldTelefoneActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(jtextfieldTelefone);
        jtextfieldTelefone.setBounds(50, 110, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpanelHeaderDialog, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpanelMainDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelHeaderDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jpanelMainDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(762, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jformattedDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jformattedDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jformattedDataActionPerformed

    private void btnCancelarDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDialogActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarDialogActionPerformed

    private void btnSalvarDiaologActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDiaologActionPerformed
        // TODO add your handling code here:

        if (jtextfieldNome.getText().isBlank() || jtextfieldCrm.getText().isBlank() || jtexfieldEmail.getText().isBlank() || jtextfieldTelefone.getText().isBlank() == true) {

            JOptionPane.showMessageDialog(this, "Por favor insira os caracteres necessários");
        } else {
            if (operacao == OperacaoEnum.Adicionar) {
                adicionar();
            } else {
                editar();
            }

        }
    }//GEN-LAST:event_btnSalvarDiaologActionPerformed

    private void JbuttonRemoverEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonRemoverEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbuttonRemoverEspecialidadeActionPerformed

    private void jtextfieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldNomeActionPerformed

    private void jtexfieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtexfieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtexfieldCodigoActionPerformed

    private void jtexfieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtexfieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtexfieldEmailActionPerformed

    private void jtextfieldCrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldCrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldCrmActionPerformed

    private void jtextfieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldTelefoneActionPerformed
    private void editar() {
        medico.setNome(jtextfieldNome.getText());
        medico.setCrm(jtextfieldCrm.getText());
        medico.setEmail(jtexfieldEmail.getText());
        medico.setTelefone(jtextfieldTelefone.getText());
        medico.setDataFormatada(jformattedData.getText());
        MedicoDAO.atualizar(medico);
        JOptionPane.showMessageDialog(this, "Gravado Com sucesso", " Plano De Saúde", JOptionPane.INFORMATION_MESSAGE);
        dispose();

    }
    

    private void adicionar() {
        Medico NovoMedico = new Medico();
        NovoMedico.setNome(jtextfieldNome.getText());
        NovoMedico.setCrm(jtextfieldCrm.getText());
        NovoMedico.setEmail(jtexfieldEmail.getText());
        NovoMedico.setTelefone(jtextfieldTelefone.getText());
        NovoMedico.setDataFormatada(jformattedData.getText());
        MedicoDAO.gravar(NovoMedico);
        JOptionPane.showMessageDialog(this, "Gravado Com sucesso", " Plano de Saúde", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonMoverEspecialidade;
    private javax.swing.JButton JbuttonRemoverEspecialidade;
    private javax.swing.JList<String> JlistEspecialidadeMedico;
    private javax.swing.JList<String> JlistListadeEspecialidadades;
    private javax.swing.JButton btnCancelarDialog;
    private javax.swing.JButton btnSalvarDiaolog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField jformattedData;
    private javax.swing.JLabel jlabelCodigo1;
    private javax.swing.JLabel jlabelCrm;
    private javax.swing.JLabel jlabelEmail;
    private javax.swing.JLabel jlabelImgLogo;
    private javax.swing.JLabel jlabelNome2;
    private javax.swing.JLabel jlabelTelefone;
    private javax.swing.JLabel jlabelTitleDialog;
    private javax.swing.JLabel jlabelValidade;
    private javax.swing.JPanel jpanelHeaderDialog;
    private javax.swing.JPanel jpanelMainDialog;
    private javax.swing.JTextField jtexfieldCodigo;
    private javax.swing.JTextField jtexfieldEmail;
    private javax.swing.JTextField jtextfieldCrm;
    private javax.swing.JTextField jtextfieldNome;
    private javax.swing.JTextField jtextfieldTelefone;
    // End of variables declaration//GEN-END:variables
}
