/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pacote.code.frame;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import pacote.code.dao.EspecialidadeDAO;
import pacote.code.dao.PlanoDeSaudeDAO;
import pacote.code.model.Especialidade;
import pacote.code.model.OperacaoEnum;
import pacote.code.model.PlanoDeSaude;

/**
 *
 * @author 22282173
 */
public class PlanoDeSaudePanel extends javax.swing.JPanel {

    /**
     * Creates new form PlanoDeSaudePanel
     */
    private int linha;

    public PlanoDeSaudePanel() {
        initComponents();
        PlanoDeSaudeDAO.criarListaDePlanoDeSaude();
        ajustarTabela();
        prencherTabela();
    }

    private int getLinha() {
        linha = tabelaPlanoDeSaude.getSelectedRow();
        return linha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        jpanelHomePlanoDeSaude = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPlanoDeSaude = new javax.swing.JTable();
        btnLimparPlanoDeSaude = new javax.swing.JButton();
        btnEditarPlanoDeSaude = new javax.swing.JButton();
        btnAdicionarPlanoDeSaude = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEspecialidades1 = new javax.swing.JTable();
        btnLimpar1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnAdicionar1 = new javax.swing.JButton();

        setLayout(null);

        jpanel.setLayout(null);

        jpanelHomePlanoDeSaude.setBackground(new java.awt.Color(255, 255, 255));
        jpanelHomePlanoDeSaude.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Plano De Saúde", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 102, 0))); // NOI18N
        jpanelHomePlanoDeSaude.setForeground(new java.awt.Color(255, 255, 255));

        tabelaPlanoDeSaude.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        tabelaPlanoDeSaude.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaPlanoDeSaude.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaPlanoDeSaude);

        javax.swing.GroupLayout jpanelHomePlanoDeSaudeLayout = new javax.swing.GroupLayout(jpanelHomePlanoDeSaude);
        jpanelHomePlanoDeSaude.setLayout(jpanelHomePlanoDeSaudeLayout);
        jpanelHomePlanoDeSaudeLayout.setHorizontalGroup(
            jpanelHomePlanoDeSaudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        jpanelHomePlanoDeSaudeLayout.setVerticalGroup(
            jpanelHomePlanoDeSaudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelHomePlanoDeSaudeLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpanel.add(jpanelHomePlanoDeSaude);
        jpanelHomePlanoDeSaude.setBounds(0, 10, 820, 350);

        btnLimparPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/excluir (1).png"))); // NOI18N
        btnLimparPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPlanoDeSaudeActionPerformed(evt);
            }
        });
        jpanel.add(btnLimparPlanoDeSaude);
        btnLimparPlanoDeSaude.setBounds(630, 370, 57, 33);

        btnEditarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/caneta.png"))); // NOI18N
        btnEditarPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPlanoDeSaudeActionPerformed(evt);
            }
        });
        jpanel.add(btnEditarPlanoDeSaude);
        btnEditarPlanoDeSaude.setBounds(690, 370, 57, 33);

        btnAdicionarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/plus.png"))); // NOI18N
        btnAdicionarPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPlanoDeSaudeActionPerformed(evt);
            }
        });
        jpanel.add(btnAdicionarPlanoDeSaude);
        btnAdicionarPlanoDeSaude.setBounds(750, 370, 57, 33);

        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Especialidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        tabelaEspecialidades1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        tabelaEspecialidades1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaEspecialidades1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaEspecialidades1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 10, 820, 350);

        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/excluir (1).png"))); // NOI18N
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpar1);
        btnLimpar1.setBounds(630, 370, 57, 33);

        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/caneta.png"))); // NOI18N
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar1);
        btnEditar1.setBounds(690, 370, 57, 33);

        btnAdicionar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/code/frame/plus.png"))); // NOI18N
        btnAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdicionar1);
        btnAdicionar1.setBounds(750, 370, 57, 33);

        jpanel.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        add(jpanel);
        jpanel.setBounds(-1, -3, 830, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPlanoDeSaudeActionPerformed
        // TODO add your handling code here:
              getLinha();
        if (getLinha() != -1) {
            excluirPlanoDeSaude();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Nenhuma linha selecionada, Por favor Selecione!!",
                    "Atenção", JOptionPane.WARNING_MESSAGE,
                    null
            );
        }


    }//GEN-LAST:event_btnLimparPlanoDeSaudeActionPerformed
        private void excluirPlanoDeSaude() {

        getLinha();
        Integer coluna = 0;

        int resposta = JOptionPane.showConfirmDialog(this,
                "Você deseja escluir esse Plano De Saúde",
                "Confirmação", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (resposta == 0) {
            PlanoDeSaudeDAO.excluirPlanoDeSaude(getCodigo());
            prencherTabela();
        }

    }
    private void btnEditarPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPlanoDeSaudeActionPerformed
        // TODO add your handling code here:

            if (getLinha() != -1) {
            editarPlanoDeSAude();

        } else {
            JOptionPane.showMessageDialog(null,
                    "Por favor clique na especialidade desejavel",
                    "Atenção",
                    JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_btnEditarPlanoDeSaudeActionPerformed

    private void btnAdicionarPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPlanoDeSaudeActionPerformed
        // TODO add your handling code here:
        PlanoDeSaudeDialog planoDeSaudeDialog = new PlanoDeSaudeDialog(null, true, OperacaoEnum.Adicionar);
        planoDeSaudeDialog.setVisible(true);
        prencherTabela();

    }//GEN-LAST:event_btnAdicionarPlanoDeSaudeActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        // TODO add your handling code here:
      

    }//GEN-LAST:event_btnLimpar1ActionPerformed
    

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnAdicionar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar1;
    private javax.swing.JButton btnAdicionarPlanoDeSaude;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEditarPlanoDeSaude;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnLimparPlanoDeSaude;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpanel;
    private javax.swing.JPanel jpanelHomePlanoDeSaude;
    private javax.swing.JTable tabelaEspecialidades1;
    private javax.swing.JTable tabelaPlanoDeSaude;
    // End of variables declaration//GEN-END:variables
 private void prencherTabela() {

        tabelaPlanoDeSaude.setModel(PlanoDeSaudeDAO.getPlanoDeSaudeModel());
        ajustarTabela();

    }

    private void ajustarTabela() {
        tabelaPlanoDeSaude.getTableHeader().setReorderingAllowed(false);
        tabelaPlanoDeSaude.setDefaultEditor(Object.class, null);
        tabelaPlanoDeSaude.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelaPlanoDeSaude.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaPlanoDeSaude.getColumnModel().getColumn(2).setPreferredWidth(200);
        tabelaPlanoDeSaude.getColumnModel().getColumn(3).setPreferredWidth(200);
        tabelaPlanoDeSaude.getColumnModel().getColumn(3).setPreferredWidth(210);
        tabelaPlanoDeSaude.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

    }

    private Integer getCodigo() {
        String codigoStr = tabelaPlanoDeSaude.getValueAt(getLinha(), 0).toString();
        Integer codigo = Integer.valueOf(codigoStr);
        return codigo;
    }

    private void editarPlanoDeSAude() {
 
    PlanoDeSaude planodesaude = PlanoDeSaudeDAO.getPlanoDeSaude(getCodigo());
    PlanoDeSaudeDialog planodesaudedialog = new PlanoDeSaudeDialog(null, true, planodesaude, OperacaoEnum.Editar);
        planodesaudedialog.setVisible(true);
        prencherTabela();
    }

}
