/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pacode.code.frame;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import pacote.code.dao.EspecialidadeDAO;

/**
 *
 * @author 22282173
 */
public class EspecialidadePanel extends javax.swing.JPanel {

    /**
     * Creates new form EspecialidadePanel
     */
    public EspecialidadePanel() {
        initComponents();
        EspecialidadeDAO.criarListaDeEspecialidades();
        ajustarTabela();
         prencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEspecialidades = new javax.swing.JTable();
        btnLimpar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Especialidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        tabelaEspecialidades.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        tabelaEspecialidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaEspecialidades.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaEspecialidades);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 10, 810, 350);

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacode/code/frame/excluir (1).png"))); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        add(btnLimpar);
        btnLimpar.setBounds(630, 370, 57, 33);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacode/code/frame/caneta.png"))); // NOI18N
        add(btnEditar);
        btnEditar.setBounds(690, 370, 57, 33);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacode/code/frame/plus.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        add(btnAdicionar);
        btnAdicionar.setBounds(750, 370, 57, 33);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        Integer linha = tabelaEspecialidades.getSelectedRow();
        if(linha != -1){
           escluirEspecialidade();
        }else{
            JOptionPane.showMessageDialog(this, 
                    "Nenhuma linha selecionada, Por favor Selecione!!", 
                    "Atenção", JOptionPane.WARNING_MESSAGE, 
                    null
            
            );
        }
        
        
    }//GEN-LAST:event_btnLimparActionPerformed
    private void escluirEspecialidade(){
    
        Integer linha = tabelaEspecialidades.getSelectedRow();
        Integer coluna = 0;
        String codigoString = tabelaEspecialidades.getValueAt(linha, coluna).toString();
        Integer codigo = Integer.valueOf(codigoString);
       int resposta =  JOptionPane.showConfirmDialog(this, "Você deseja escluir essa especialidade", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        EspecialidadeDAO.excluirEspecialidade(codigo);
        prencherTabela();
    }
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        EspecialidadeDialog especialidadeDialog = new EspecialidadeDialog(null, true);
        especialidadeDialog.setVisible(true);
        prencherTabela();
      
        
    }//GEN-LAST:event_btnAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEspecialidades;
    // End of variables declaration//GEN-END:variables

    private void prencherTabela() {
       
        tabelaEspecialidades.setModel(EspecialidadeDAO.getEspecialidadesModel());
        ajustarTabela();

    }
    private void ajustarTabela(){
        tabelaEspecialidades.getTableHeader().setReorderingAllowed(false);
        tabelaEspecialidades.setDefaultEditor(Object.class, null);
        tabelaEspecialidades.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelaEspecialidades.getColumnModel().getColumn(1).setPreferredWidth(300);
        tabelaEspecialidades.getColumnModel().getColumn(2).setPreferredWidth(395);
        tabelaEspecialidades.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
       
        
    }

}
