/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pacode.code.frame;

import javax.swing.JOptionPane;
import pacote.code.dao.EspecialidadeDAO;
import pacote.code.model.Especialidade;

/**
 *
 * @author 22282173
 */
public class EspecialidadeDialog extends javax.swing.JDialog {

    /**
     * Creates new form EspecialidadeDialog
     */
    public EspecialidadeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelHeaderDialog = new javax.swing.JPanel();
        jlabelTitleDialog = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpanelMainDialog = new javax.swing.JPanel();
        jtextfieldCodigo = new javax.swing.JTextField();
        jtextfieldNomeEspecialidade = new javax.swing.JTextField();
        jtextfieldDescricaoEspecialidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalvarDiaolog = new javax.swing.JButton();
        btnCancelarDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar");
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jpanelHeaderDialog.setBackground(new java.awt.Color(255, 153, 0));
        jpanelHeaderDialog.setLayout(null);

        jlabelTitleDialog.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlabelTitleDialog.setForeground(new java.awt.Color(255, 255, 255));
        jlabelTitleDialog.setText("Especialidades Adicionar");
        jpanelHeaderDialog.add(jlabelTitleDialog);
        jlabelTitleDialog.setBounds(20, 20, 290, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacode/code/frame/adicionarCoisas.png"))); // NOI18N
        jpanelHeaderDialog.add(jLabel4);
        jLabel4.setBounds(320, 20, 40, 40);

        getContentPane().add(jpanelHeaderDialog);
        jpanelHeaderDialog.setBounds(0, 0, 800, 70);

        jpanelMainDialog.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes da especialidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 102, 0))); // NOI18N
        jpanelMainDialog.setLayout(null);

        jtextfieldCodigo.setEditable(false);
        jtextfieldCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        jtextfieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldCodigoActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(jtextfieldCodigo);
        jtextfieldCodigo.setBounds(50, 60, 80, 30);

        jtextfieldNomeEspecialidade.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        jtextfieldNomeEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldNomeEspecialidadeActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(jtextfieldNomeEspecialidade);
        jtextfieldNomeEspecialidade.setBounds(50, 210, 460, 30);

        jtextfieldDescricaoEspecialidade.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        jtextfieldDescricaoEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldDescricaoEspecialidadeActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(jtextfieldDescricaoEspecialidade);
        jtextfieldDescricaoEspecialidade.setBounds(50, 130, 460, 30);

        jLabel1.setText("DESCRIÇÂO DA ESPECIALIDADE");
        jpanelMainDialog.add(jLabel1);
        jLabel1.setBounds(50, 190, 210, 16);

        jLabel2.setText("CODIGO");
        jpanelMainDialog.add(jLabel2);
        jLabel2.setBounds(50, 40, 50, 20);

        jLabel3.setText("NOME DA ESPECIALIDADE");
        jpanelMainDialog.add(jLabel3);
        jLabel3.setBounds(50, 110, 140, 16);

        btnSalvarDiaolog.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvarDiaolog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacode/code/frame/salvar.png"))); // NOI18N
        btnSalvarDiaolog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDiaologActionPerformed(evt);
            }
        });
        jpanelMainDialog.add(btnSalvarDiaolog);
        btnSalvarDiaolog.setBounds(630, 253, 50, 40);

        btnCancelarDialog.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacode/code/frame/excluir (4).png"))); // NOI18N
        jpanelMainDialog.add(btnCancelarDialog);
        btnCancelarDialog.setBounds(570, 253, 50, 40);

        getContentPane().add(jpanelMainDialog);
        jpanelMainDialog.setBounds(40, 90, 700, 310);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfieldNomeEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldNomeEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldNomeEspecialidadeActionPerformed

    private void jtextfieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldCodigoActionPerformed

    private void jtextfieldDescricaoEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldDescricaoEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldDescricaoEspecialidadeActionPerformed

    private void btnSalvarDiaologActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDiaologActionPerformed
        // TODO add your handling code here:
        Especialidade especialidade = new Especialidade();
        especialidade.setNome(jtextfieldNomeEspecialidade.getText());
        especialidade.setDescricao(jtextfieldDescricaoEspecialidade.getText());
        // Gravar o objeto, através do dao
        EspecialidadeDAO.gravar(especialidade);
        //JOptionPane.showMessageDialog(this, "Gravado Com sucesso", " Especialidade", JOptionPane.INFORMATION_MESSAGE);
        dispose();
        
    }//GEN-LAST:event_btnSalvarDiaologActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EspecialidadeDialog dialog = new EspecialidadeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarDialog;
    private javax.swing.JButton btnSalvarDiaolog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlabelTitleDialog;
    private javax.swing.JPanel jpanelHeaderDialog;
    private javax.swing.JPanel jpanelMainDialog;
    private javax.swing.JTextField jtextfieldCodigo;
    private javax.swing.JTextField jtextfieldDescricaoEspecialidade;
    private javax.swing.JTextField jtextfieldNomeEspecialidade;
    // End of variables declaration//GEN-END:variables
}
